[package]
name = "advent2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
criterion = "0.4.0"
hashers = "1.0.1"
nom = "7.1.1"

[[bench]]
name = "advent"
harness = false
